/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author AseemD
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    private DeliveryPackage delPackage;
    private Boolean validate = false;
    
    public CreateJPanel(){
    initComponents();
    }
    
    CreateJPanel(DeliveryPackage deliveryPackage){
    initComponents();
    
    // LOGIC TO TAKE INFORMATION FROM THE USER AND STORE IT IN THE DELIVERY PACKAGE
    this.delPackage = deliveryPackage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        packageId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        packageWt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productId1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        productName1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        productPrice1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        custName1 = new javax.swing.JTextField();
        custId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        saveProductbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Package ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 100, -1));

        jLabel2.setText("Weight");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, -1));
        add(packageWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 100, -1));

        jLabel3.setText("ProdId");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        add(productId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 100, -1));

        jLabel4.setText("ProdName");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, -1));

        jLabel5.setText("ProdPrice");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        add(productPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 100, -1));

        jLabel6.setText("Customer Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel7.setText("ID");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        custName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custName1ActionPerformed(evt);
            }
        });
        add(custName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 120, -1));
        add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 120, -1));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        saveProductbtn.setText("SAVE PRODUCT");
        saveProductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductbtnActionPerformed(evt);
            }
        });
        add(saveProductbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void custName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custName1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        // GET THE DATA
        
        String id = packageId.getText();
        String weight = packageWt.getText();
        
        String customerId = custId.getText();
        String customername = custName1.getText();
        
        // STORE THE DATA
        
        this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));
        
        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerId(Integer.valueOf(customerId));
        customer.setName(customername);
        
        if(validate){
            JOptionPane.showMessageDialog(null, "Please fill all fields");
          } else{
            JOptionPane.showMessageDialog(null, "Saved!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void saveProductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductbtnActionPerformed
        // TODO add your handling code here:
        
        String productId = productId1.getText();
        String productName = productName1.getText();
        String productPrice = productPrice1.getText();
        
        Product product = this.delPackage.createProduct(Integer.valueOf(productId), productName, Double.valueOf(productPrice));
        JOptionPane.showMessageDialog(null, "Added Product!");
    }//GEN-LAST:event_saveProductbtnActionPerformed

    private void custName1FocusLost(java.awt.event.FocusEvent evt){
        
        System.out.println(custName1.getText() + "-- The customer name");
        String name = custName1.getText();
        
        if(name.isEmpty()){
            this.validate = true;
          } else{
            this.validate = false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField custId;
    private javax.swing.JTextField custName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWt;
    private javax.swing.JTextField productId1;
    private javax.swing.JTextField productName1;
    private javax.swing.JTextField productPrice1;
    private javax.swing.JButton saveProductbtn;
    // End of variables declaration//GEN-END:variables
}
