/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Application;

/**
 *
 * @author AseemD
 */
public class MainJFrame extends javax.swing.JFrame {

            Application application;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.application = new Application();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ControlJPanel = new javax.swing.JPanel();
        createObservationbtn = new javax.swing.JButton();
        viewVitalsbtn = new javax.swing.JButton();
        medicineCatalogbtn = new javax.swing.JButton();
        medicineAssignbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ControlJPanel.setBackground(new java.awt.Color(215, 255, 204));
        ControlJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createObservationbtn.setText("CREATE OBSERVATION");
        createObservationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createObservationbtnActionPerformed(evt);
            }
        });
        ControlJPanel.add(createObservationbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 170, -1));

        viewVitalsbtn.setText("VIEW VITAL SIGN HISTORY");
        viewVitalsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVitalsbtnActionPerformed(evt);
            }
        });
        ControlJPanel.add(viewVitalsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        medicineCatalogbtn.setText("MEDICINE CATALOG");
        medicineCatalogbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineCatalogbtnActionPerformed(evt);
            }
        });
        ControlJPanel.add(medicineCatalogbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 170, -1));

        medicineAssignbtn.setText("ASSIGN MEDICINE");
        medicineAssignbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineAssignbtnActionPerformed(evt);
            }
        });
        ControlJPanel.add(medicineAssignbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 170, -1));

        jSplitPane1.setLeftComponent(ControlJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createObservationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createObservationbtnActionPerformed
        // TODO add your handling code here:
        
        jSplitPane1.setRightComponent(new CreateJPanel(this.application));
    }//GEN-LAST:event_createObservationbtnActionPerformed

    private void viewVitalsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVitalsbtnActionPerformed

        // TODO add your handling code here:
        
        jSplitPane1.setRightComponent(new ViewJPanel(this.application));
    }//GEN-LAST:event_viewVitalsbtnActionPerformed

    private void medicineCatalogbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineCatalogbtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CatalogJPanel(this.application));
    }//GEN-LAST:event_medicineCatalogbtnActionPerformed

    private void medicineAssignbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineAssignbtnActionPerformed
        // TODO add your handling code here:
        
        jSplitPane1.setRightComponent(new MedicineJPanel(this.application));
    }//GEN-LAST:event_medicineAssignbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlJPanel;
    private javax.swing.JButton createObservationbtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton medicineAssignbtn;
    private javax.swing.JButton medicineCatalogbtn;
    private javax.swing.JButton viewVitalsbtn;
    // End of variables declaration//GEN-END:variables
}
