/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.Observation;
import java.util.ArrayList;

/**
 *
 * @author AseemD
 */
public class MedicineJPanel extends javax.swing.JPanel {

        private Application application;

    /**
     * Creates new form MedicineJPanel
     */
 
    
    MedicineJPanel(Application application){
        initComponents();
        this.application = application;
        populateDropDowns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        observationBox = new javax.swing.JComboBox();
        medicineBox = new javax.swing.JComboBox();
        assignMedicationBtn = new javax.swing.JButton();
        showAssignedMed = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        observationBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                observationBoxItemStateChanged(evt);
            }
        });
        observationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observationBoxActionPerformed(evt);
            }
        });
        add(observationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 140, 30));

        medicineBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineBoxActionPerformed(evt);
            }
        });
        add(medicineBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 92, 130, 30));

        assignMedicationBtn.setText("ASSIGN MEDICATION");
        assignMedicationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignMedicationBtnActionPerformed(evt);
            }
        });
        add(assignMedicationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));
        add(showAssignedMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 80, 30));
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void observationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observationBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observationBoxActionPerformed

    private void observationBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_observationBoxItemStateChanged
        // TODO add your handling code here:
         Observation o = (Observation) observationBox.getSelectedItem();
        
        if(o.getMedication() != null){
            showAssignedMed.setText(o.getMedication().getMedicineName());
        }
    
    }//GEN-LAST:event_observationBoxItemStateChanged

    private void assignMedicationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignMedicationBtnActionPerformed
        // TODO add your handling code here:
        
        Observation o = (Observation) observationBox.getSelectedItem();
        Medicine m = (Medicine) medicineBox.getSelectedItem();
        
        o.setMedication(m);
        
    }//GEN-LAST:event_assignMedicationBtnActionPerformed

    private void medicineBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineBoxActionPerformed

    public void populateDropDowns(){
        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicineList();
        ArrayList<Observation> observations = this.application.getHistory().getVitalSignHistory();
        
        for(Observation o : observations){
            observationBox.addItem(o);
          }
        for(Medicine med : medicines){
            medicineBox.addItem(med);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignMedicationBtn;
    private javax.swing.JComboBox medicineBox;
    private javax.swing.JComboBox observationBox;
    private javax.swing.JLabel showAssignedMed;
    // End of variables declaration//GEN-END:variables
}
